server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Development settings (no caching)
    expires off;
    add_header Cache-Control "no-store, no-cache, must-revalidate";

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/javascript;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
